### ISSUE TITLE
Issues with typing/erasing the space character

### ISSUE THREAD

**Issue by mycielski** [0ql/Donkeytype#4]
When the caret reaches the end of a word then only the space key press is accepted. Pressing a different key than space is not recognized as an error by the game. To me that seems like a glitch. If pressing a wrong key when typing a word is an error then pressing a wrong key when typing a space should be an error too.

Also erasing spaces does not work. That might be a design choice (once a word is typed and submitted then it can't be changed) but seems like a glitch to me. If however it is a design choice then I believe a player should be allowed to disable/enable this in the settings.

**Comment by 0ql** [comment]
Ok so actually both behaviors are intended and related. When you press space you "submit" the word so you can't change it later. This behavior keeps users from having to mash their backspace button because they already typed half of the next word before noticing the mistake. I'll probably introduce different behaviors that you can choose from in the settings.

**Comment by mycielski** [comment]
I see. Well then if it is a deliberate design choice then this is a non-issue. Thank you for your answer.
